version: '3.9'

services:
  nginx-container:
    container_name: nginx-container
    image: nginx-w-extras:${NGINX_IMAGE_TAG}
    restart: unless-stopped
    build:
      context: ./config
      args:
        NGINX_IMAGE_TAG: ${NGINX_IMAGE_TAG}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/globals:/etc/nginx/globals
      - ./config/sites-available:/etc/nginx/sites-available
      - ./config/sites-enabled:/etc/nginx/sites-enabled
      - ./config/dhparams-4096.pem:/etc/nginx/dhparams-4096.pem
      - ./logs:/var/log/nginx
      - ../certbot/letsencrypt:/etc/letsencrypt:ro
    healthcheck:
      test: ["CMD", "service", "nginx", "status", "||", "exit", "1"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - web-server-network

networks:
  web-server-network:
    name: web-server-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet : 192.168.100.0/24
