version: '3.9'

services:
  nginx-container:
    container_name: hello-word
    image: hello-world:latest
    networks:
      - docker-network

networks:
  docker-network:
    name: docker-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
